Fail to get yarn configuration. /home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyterlab/staging/yarn.js:4
(()=>{var Qge=Object.create;var AS=Object.defineProperty;var bge=Object.getOwnPropertyDescriptor;var Sge=Object.getOwnPropertyNames;var vge=Object.getPrototypeOf,xge=Object.prototype.hasOwnProperty;var J=(r=>typeof require<"u"?require:typeof Proxy<"u"?new Proxy(r,{get:(e,t)=>(typeof require<"u"?require:e)[t]}):r)(function(r){if(typeof require<"u")return require.apply(this,arguments);throw new Error('Dynamic require of "'+r+'" is not supported')});var Pge=(r,e)=>()=>(r&&(e=r(r=0)),e);var w=(r,e)=>()=>(e||r((e={exports:{}}).exports,e),e.exports),ut=(r,e)=>{for(var t in e)AS(r,t,{get:e[t],enumerable:!0})},Dge=(r,e,t,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let n of Sge(e))!xge.call(r,n)&&n!==t&&AS(r,n,{get:()=>e[n],enumerable:!(i=bge(e,n))||i.enumerable});return r};var Pe=(r,e,t)=>(t=r!=null?Qge(vge(r)):{},Dge(e||!r||!r.__esModule?AS(t,"default",{value:r,enumerable:!0}):t,r));var QK=w((GXe,BK)=>{BK.expor

SyntaxError: Unexpected token {
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

[I 2024-04-02 09:41:44.600 ServerApp] Package jupyterlab took 0.0000s to import
[I 2024-04-02 09:41:45.148 ServerApp] Package jupyter_lsp took 0.5476s to import
[W 2024-04-02 09:41:45.149 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-04-02 09:41:45.437 ServerApp] Package jupyter_server_terminals took 0.2874s to import
[I 2024-04-02 09:41:45.437 ServerApp] Package notebook took 0.0000s to import
[I 2024-04-02 09:41:45.463 ServerApp] Package notebook_shim took 0.0000s to import
[W 2024-04-02 09:41:45.464 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-04-02 09:41:45.483 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-04-02 09:41:45.492 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-04-02 09:41:45.499 ServerApp] jupyterlab | extension was successfully linked.
[W 2024-04-02 09:41:45.529 JupyterNotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-04-02 09:41:45.532 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2024-04-02 09:41:45.532 ServerApp] notebook | extension was successfully linked.
[I 2024-04-02 09:41:51.704 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-04-02 09:41:52.084 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-04-02 09:41:52.088 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-04-02 09:41:52.089 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-04-02 09:41:52.176 LabApp] JupyterLab extension loaded from /home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyterlab
[I 2024-04-02 09:41:52.176 LabApp] JupyterLab application directory is /home/naglemi/miniconda3/envs/mwas/share/jupyter/lab
[I 2024-04-02 09:41:52.177 LabApp] Extension Manager is 'pypi'.
[I 2024-04-02 09:41:52.180 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-04-02 09:41:52.184 ServerApp] notebook | extension was successfully loaded.
[I 2024-04-02 09:41:52.185 ServerApp] Serving notebooks from local directory: /expanse/lustre/projects/jhu152/naglemi/mwas/CpGWAS
[I 2024-04-02 09:41:52.185 ServerApp] Jupyter Server 2.10.0 is running at:
[I 2024-04-02 09:41:52.185 ServerApp] http://localhost:8888/lab
[I 2024-04-02 09:41:52.185 ServerApp]     http://127.0.0.1:8888/lab
[I 2024-04-02 09:41:52.186 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[?1049h[22;0;0t[1;24r(B[m[4l[?7h[?1h=[39;49m[39;49m[37m[40m[H[2J[37m[40m[J(B[m[39;49m[37m[40m[39;49m[37m[40m[J[39;49m(B[m[22d[93m[44mGetting file://localhost/home/naglemi/.local/share/jupyter/runtime/jpserver-321[K[39;49m(B[m

[24;1H[?1049l[23;0;0t[?1l>[I 2024-04-02 09:42:00.043 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2024-04-02 09:52:23.999 ServerApp] 302 GET / (@127.0.0.1) 0.65ms
0.02s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[W 2024-04-02 09:52:31.687 LabApp] Could not determine jupyterlab build status without nodejs
[W 2024-04-02 09:52:35.659 ServerApp] 404 GET /api/contents/CpGWAS/scripts/07_Deploy_SLURM.ipynb?content=0&1712076755619 (127.0.0.1): No such file or directory: CpGWAS/scripts/07_Deploy_SLURM.ipynb
[W 2024-04-02 09:52:35.659 ServerApp] wrote error: 'No such file or directory: CpGWAS/scripts/07_Deploy_SLURM.ipynb'
    Traceback (most recent call last):
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/filemanager.py", line 863, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: CpGWAS/scripts/07_Deploy_SLURM.ipynb)
[W 2024-04-02 09:52:35.750 ServerApp] 404 GET /api/contents/CpGWAS/scripts/07_Deploy_SLURM.ipynb?content=0&1712076755619 (6babfdbb47c7410480cafbb1b83d7c96@127.0.0.1) 92.14ms referer=http://localhost:8892/lab?
[W 2024-04-02 09:52:35.750 ServerApp] 404 GET /api/contents/CpGWAS/scripts/07_Deploy_SLURM_a2.ipynb?content=0&1712076755619 (127.0.0.1): No such file or directory: CpGWAS/scripts/07_Deploy_SLURM_a2.ipynb
[W 2024-04-02 09:52:35.750 ServerApp] wrote error: 'No such file or directory: CpGWAS/scripts/07_Deploy_SLURM_a2.ipynb'
    Traceback (most recent call last):
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/filemanager.py", line 863, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: CpGWAS/scripts/07_Deploy_SLURM_a2.ipynb)
[W 2024-04-02 09:52:35.751 ServerApp] 404 GET /api/contents/CpGWAS/scripts/07_Deploy_SLURM_a2.ipynb?content=0&1712076755619 (6babfdbb47c7410480cafbb1b83d7c96@127.0.0.1) 92.84ms referer=http://localhost:8892/lab?
[I 2024-04-02 09:52:36.021 ServerApp] New terminal with automatic name: 1
[W 2024-04-02 09:52:37.099 ServerApp] 404 GET /api/contents/CpGWAS/scripts?1712076757060 (127.0.0.1): No such file or directory: CpGWAS/scripts
[W 2024-04-02 09:52:37.099 ServerApp] wrote error: 'No such file or directory: CpGWAS/scripts'
    Traceback (most recent call last):
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/filemanager.py", line 863, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: CpGWAS/scripts)
[W 2024-04-02 09:52:37.100 ServerApp] 404 GET /api/contents/CpGWAS/scripts?1712076757060 (6babfdbb47c7410480cafbb1b83d7c96@127.0.0.1) 1.76ms referer=http://localhost:8892/lab?
[W 2024-04-02 09:52:53.988 ServerApp] Notebook scripts/05_Inspect_SLURM_benchmarks_a2.ipynb is not trusted
[I 2024-04-02 09:52:54.836 ServerApp] Kernel started: 66cec57e-800f-4505-a3e4-700eb49641e8
[I 2024-04-02 09:52:57.143 ServerApp] Connecting to kernel 66cec57e-800f-4505-a3e4-700eb49641e8.
[I 2024-04-02 09:52:57.145 ServerApp] Connecting to kernel 66cec57e-800f-4505-a3e4-700eb49641e8.
[I 2024-04-02 09:52:57.146 ServerApp] Connecting to kernel 66cec57e-800f-4505-a3e4-700eb49641e8.
[I 2024-04-02 09:53:01.533 ServerApp] Copying scripts/05_Inspect_SLURM_benchmarks_a2.ipynb to /scripts
[W 2024-04-02 09:53:01.538 ServerApp] Notebook scripts/05_Inspect_SLURM_benchmarks_a2.ipynb is not trusted
[W 2024-04-02 09:53:01.545 ServerApp] Notebook scripts/05_Inspect_SLURM_benchmarks_a2.ipynb is not trusted
[W 2024-04-02 09:53:01.546 ServerApp] Notebook scripts/05_Inspect_SLURM_benchmarks_a2-Copy1.ipynb is not trusted
[W 2024-04-02 09:53:08.337 ServerApp] Notebook scripts/05_Inspect_SLURM_benchmarks_a3.ipynb is not trusted
[I 2024-04-02 09:53:08.879 ServerApp] Kernel started: 4cfc1db4-0441-4309-8643-eac6a25b5b74
[I 2024-04-02 09:53:09.709 ServerApp] Starting buffering for 66cec57e-800f-4505-a3e4-700eb49641e8:bbbbda1c-5d85-46ed-a343-10e85988aa74
[I 2024-04-02 09:53:10.138 ServerApp] Connecting to kernel 4cfc1db4-0441-4309-8643-eac6a25b5b74.
[I 2024-04-02 09:54:40.674 ServerApp] Kernel restarted: 4cfc1db4-0441-4309-8643-eac6a25b5b74
[I 2024-04-02 09:54:40.792 ServerApp] Starting buffering for 4cfc1db4-0441-4309-8643-eac6a25b5b74:71c8b920-f1cb-407c-adb8-9e46fbbc0ce8
[I 2024-04-02 09:54:40.932 ServerApp] Connecting to kernel 4cfc1db4-0441-4309-8643-eac6a25b5b74.
[I 2024-04-02 09:54:40.932 ServerApp] Restoring connection for 4cfc1db4-0441-4309-8643-eac6a25b5b74:71c8b920-f1cb-407c-adb8-9e46fbbc0ce8
[I 2024-04-02 09:55:08.766 ServerApp] Saving file at /scripts/05_Inspect_SLURM_benchmarks_a3.ipynb
[I 2024-04-02 09:55:22.473 ServerApp] Kernel shutdown: 66cec57e-800f-4505-a3e4-700eb49641e8
[I 2024-04-02 09:55:22.540 ServerApp] EOF on FD 16; stopping reading
[I 2024-04-02 09:55:22.641 ServerApp] Terminal 1 closed
[I 2024-04-02 09:55:22.645 ServerApp] Kernel shutdown: 4cfc1db4-0441-4309-8643-eac6a25b5b74
[I 2024-04-02 09:55:23.081 ServerApp] Shutting down on /api/shutdown request.
[I 2024-04-02 09:55:23.107 ServerApp] Shutting down 5 extensions
