Fail to get yarn configuration. /home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyterlab/staging/yarn.js:4
(()=>{var Qge=Object.create;var AS=Object.defineProperty;var bge=Object.getOwnPropertyDescriptor;var Sge=Object.getOwnPropertyNames;var vge=Object.getPrototypeOf,xge=Object.prototype.hasOwnProperty;var J=(r=>typeof require<"u"?require:typeof Proxy<"u"?new Proxy(r,{get:(e,t)=>(typeof require<"u"?require:e)[t]}):r)(function(r){if(typeof require<"u")return require.apply(this,arguments);throw new Error('Dynamic require of "'+r+'" is not supported')});var Pge=(r,e)=>()=>(r&&(e=r(r=0)),e);var w=(r,e)=>()=>(e||r((e={exports:{}}).exports,e),e.exports),ut=(r,e)=>{for(var t in e)AS(r,t,{get:e[t],enumerable:!0})},Dge=(r,e,t,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let n of Sge(e))!xge.call(r,n)&&n!==t&&AS(r,n,{get:()=>e[n],enumerable:!(i=bge(e,n))||i.enumerable});return r};var Pe=(r,e,t)=>(t=r!=null?Qge(vge(r)):{},Dge(e||!r||!r.__esModule?AS(t,"default",{value:r,enumerable:!0}):t,r));var QK=w((GXe,BK)=>{BK.expor

SyntaxError: Unexpected token {
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

[I 2024-02-26 07:36:09.908 ServerApp] Package jupyterlab took 0.0000s to import
[I 2024-02-26 07:36:10.475 ServerApp] Package jupyter_lsp took 0.5660s to import
[W 2024-02-26 07:36:10.475 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-02-26 07:36:10.790 ServerApp] Package jupyter_server_terminals took 0.3147s to import
[I 2024-02-26 07:36:10.790 ServerApp] Package notebook took 0.0000s to import
[I 2024-02-26 07:36:10.812 ServerApp] Package notebook_shim took 0.0000s to import
[W 2024-02-26 07:36:10.812 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-02-26 07:36:10.847 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-02-26 07:36:10.852 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-02-26 07:36:10.857 ServerApp] jupyterlab | extension was successfully linked.
[W 2024-02-26 07:36:10.872 JupyterNotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-02-26 07:36:10.874 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2024-02-26 07:36:10.874 ServerApp] notebook | extension was successfully linked.
[I 2024-02-26 07:36:16.376 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-02-26 07:36:16.900 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-02-26 07:36:16.902 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-02-26 07:36:16.903 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-02-26 07:36:16.947 LabApp] JupyterLab extension loaded from /home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyterlab
[I 2024-02-26 07:36:16.947 LabApp] JupyterLab application directory is /home/naglemi/miniconda3/envs/mwas/share/jupyter/lab
[I 2024-02-26 07:36:16.948 LabApp] Extension Manager is 'pypi'.
[I 2024-02-26 07:36:16.949 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-02-26 07:36:16.952 ServerApp] notebook | extension was successfully loaded.
[I 2024-02-26 07:36:16.953 ServerApp] Serving notebooks from local directory: /expanse/lustre/projects/jhu152/naglemi/mwas/CpGWAS
[I 2024-02-26 07:36:16.953 ServerApp] Jupyter Server 2.10.0 is running at:
[I 2024-02-26 07:36:16.953 ServerApp] http://localhost:8888/lab
[I 2024-02-26 07:36:16.953 ServerApp]     http://127.0.0.1:8888/lab
[I 2024-02-26 07:36:16.953 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[?1049h[22;0;0t[1;24r(B[m[4l[?7h[?1h=[39;49m[39;49m[37m[40m[H[2J[37m[40m[J(B[m[39;49m[37m[40m[39;49m[37m[40m[J[39;49m(B[m[22d[93m[44mGetting file://localhost/home/naglemi/.local/share/jupyter/runtime/jpserver-138[K[39;49m(B[m

[24;1H[?1049l[23;0;0t[?1l>[I 2024-02-26 07:36:26.122 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2024-02-26 07:36:28.178 ServerApp] 302 GET / (@127.0.0.1) 0.39ms
0.05s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[W 2024-02-26 07:36:35.887 LabApp] Could not determine jupyterlab build status without nodejs
[W 2024-02-26 07:36:36.220 ServerApp] 404 GET /api/contents/mwas/CpGWAS/scripts/06_Evaluate_plot_parameters_a9-Copy1.ipynb?content=0&1708961796164 (127.0.0.1): No such file or directory: mwas/CpGWAS/scripts/06_Evaluate_plot_parameters_a9-Copy1.ipynb
[W 2024-02-26 07:36:36.220 ServerApp] wrote error: 'No such file or directory: mwas/CpGWAS/scripts/06_Evaluate_plot_parameters_a9-Copy1.ipynb'
    Traceback (most recent call last):
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/filemanager.py", line 863, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: mwas/CpGWAS/scripts/06_Evaluate_plot_parameters_a9-Copy1.ipynb)
[W 2024-02-26 07:36:36.224 ServerApp] 404 GET /api/contents/mwas/CpGWAS/scripts/06_Evaluate_plot_parameters_a9-Copy1.ipynb?content=0&1708961796164 (f406b51829c04f75a21c912f4e62bf04@127.0.0.1) 5.06ms referer=http://localhost:8892/lab?
[W 2024-02-26 07:36:36.225 ServerApp] 404 GET /api/contents/mwas/CpGWAS/scripts/07_Deploy_SLURM.ipynb?content=0&1708961796164 (127.0.0.1): No such file or directory: mwas/CpGWAS/scripts/07_Deploy_SLURM.ipynb
[W 2024-02-26 07:36:36.225 ServerApp] wrote error: 'No such file or directory: mwas/CpGWAS/scripts/07_Deploy_SLURM.ipynb'
    Traceback (most recent call last):
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/filemanager.py", line 863, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: mwas/CpGWAS/scripts/07_Deploy_SLURM.ipynb)
[W 2024-02-26 07:36:36.225 ServerApp] 404 GET /api/contents/mwas/CpGWAS/scripts/07_Deploy_SLURM.ipynb?content=0&1708961796164 (f406b51829c04f75a21c912f4e62bf04@127.0.0.1) 0.96ms referer=http://localhost:8892/lab?
[W 2024-02-26 07:36:37.114 ServerApp] 404 GET /api/contents/mwas/CpGWAS?1708961797061 (127.0.0.1): No such file or directory: mwas/CpGWAS
[W 2024-02-26 07:36:37.115 ServerApp] wrote error: 'No such file or directory: mwas/CpGWAS'
    Traceback (most recent call last):
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/filemanager.py", line 863, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: mwas/CpGWAS)
[W 2024-02-26 07:36:37.115 ServerApp] 404 GET /api/contents/mwas/CpGWAS?1708961797061 (f406b51829c04f75a21c912f4e62bf04@127.0.0.1) 1.49ms referer=http://localhost:8892/lab?
[I 2024-02-26 07:36:51.596 ServerApp] Kernel started: fbc31e48-4128-4bfc-b740-877a110c5254
[I 2024-02-26 07:36:54.639 ServerApp] Connecting to kernel fbc31e48-4128-4bfc-b740-877a110c5254.
[I 2024-02-26 07:36:54.640 ServerApp] Connecting to kernel fbc31e48-4128-4bfc-b740-877a110c5254.
[I 2024-02-26 07:36:54.641 ServerApp] Connecting to kernel fbc31e48-4128-4bfc-b740-877a110c5254.
[I 2024-02-26 07:38:51.335 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
[I 2024-02-26 07:40:52.037 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
[I 2024-02-26 07:42:31.064 ServerApp] Kernel restarted: fbc31e48-4128-4bfc-b740-877a110c5254
[I 2024-02-26 07:42:31.140 ServerApp] Starting buffering for fbc31e48-4128-4bfc-b740-877a110c5254:0ba6345c-f805-43ec-a232-7a97f7f34385
[I 2024-02-26 07:42:31.274 ServerApp] Connecting to kernel fbc31e48-4128-4bfc-b740-877a110c5254.
[I 2024-02-26 07:42:31.274 ServerApp] Restoring connection for fbc31e48-4128-4bfc-b740-877a110c5254:0ba6345c-f805-43ec-a232-7a97f7f34385
[I 2024-02-26 07:42:52.551 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
sbatch: error: Invalid directive found in batch script: shared
sbatch: error: Invalid directive found in batch script: shared
[I 2024-02-26 07:44:53.481 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
[I 2024-02-26 07:46:51.276 ServerApp] Kernel restarted: fbc31e48-4128-4bfc-b740-877a110c5254
[I 2024-02-26 07:46:51.351 ServerApp] Starting buffering for fbc31e48-4128-4bfc-b740-877a110c5254:0ba6345c-f805-43ec-a232-7a97f7f34385
[I 2024-02-26 07:46:51.491 ServerApp] Connecting to kernel fbc31e48-4128-4bfc-b740-877a110c5254.
[I 2024-02-26 07:46:51.491 ServerApp] Restoring connection for fbc31e48-4128-4bfc-b740-877a110c5254:0ba6345c-f805-43ec-a232-7a97f7f34385
sbatch: error: Invalid directive found in batch script: shared
[I 2024-02-26 07:46:54.021 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
sbatch: error: Invalid directive found in batch script: shared
sbatch: error: Invalid directive found in batch script: shared
[I 2024-02-26 07:48:54.551 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
sbatch: error: bank_limit plugin: Please set the ntasks or ntasks-per-node parameter
sbatch: error: Batch job submission failed: Requested operation not supported on this system
sbatch: error: bank_limit plugin: Please set the ntasks or ntasks-per-node parameter
sbatch: error: Batch job submission failed: Requested operation not supported on this system
[I 2024-02-26 07:50:55.080 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
[I 2024-02-26 07:52:55.811 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
[I 2024-02-26 07:53:13.407 ServerApp] Kernel restarted: fbc31e48-4128-4bfc-b740-877a110c5254
[I 2024-02-26 07:53:13.483 ServerApp] Starting buffering for fbc31e48-4128-4bfc-b740-877a110c5254:0ba6345c-f805-43ec-a232-7a97f7f34385
[I 2024-02-26 07:53:13.619 ServerApp] Connecting to kernel fbc31e48-4128-4bfc-b740-877a110c5254.
[I 2024-02-26 07:53:13.620 ServerApp] Restoring connection for fbc31e48-4128-4bfc-b740-877a110c5254:0ba6345c-f805-43ec-a232-7a97f7f34385
Submitted batch job 28933428
Submitted batch job 28933429
[I 2024-02-26 07:54:56.444 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
[I 2024-02-26 08:40:44.484 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
[I 2024-02-26 08:41:00.367 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
[I 2024-02-26 08:41:13.115 ServerApp] Kernel restarted: fbc31e48-4128-4bfc-b740-877a110c5254
[I 2024-02-26 08:41:13.193 ServerApp] Starting buffering for fbc31e48-4128-4bfc-b740-877a110c5254:0ba6345c-f805-43ec-a232-7a97f7f34385
[I 2024-02-26 08:41:13.326 ServerApp] Connecting to kernel fbc31e48-4128-4bfc-b740-877a110c5254.
[I 2024-02-26 08:41:13.327 ServerApp] Restoring connection for fbc31e48-4128-4bfc-b740-877a110c5254:0ba6345c-f805-43ec-a232-7a97f7f34385
Submitted batch job 28934394
Submitted batch job 28934395
[I 2024-02-26 08:42:50.552 ServerApp] Creating new notebook in /scripts
[I 2024-02-26 08:42:51.699 ServerApp] Kernel started: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5
[I 2024-02-26 08:42:52.403 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 08:43:00.956 ServerApp] Saving file at /scripts/07_Deploy_SLURM.ipynb
[I 2024-02-26 08:44:51.470 ServerApp] Saving file at /scripts/Untitled2.ipynb
[I 2024-02-26 08:46:51.951 ServerApp] Saving file at /scripts/Untitled2.ipynb
[E 2024-02-26 08:47:37.412 LabApp] Fail to get yarn configuration. /home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyterlab/staging/yarn.js:4
    (()=>{var Qge=Object.create;var AS=Object.defineProperty;var bge=Object.getOwnPropertyDescriptor;var Sge=Object.getOwnPropertyNames;var vge=Object.getPrototypeOf,xge=Object.prototype.hasOwnProperty;var J=(r=>typeof require<"u"?require:typeof Proxy<"u"?new Proxy(r,{get:(e,t)=>(typeof require<"u"?require:e)[t]}):r)(function(r){if(typeof require<"u")return require.apply(this,arguments);throw new Error('Dynamic require of "'+r+'" is not supported')});var Pge=(r,e)=>()=>(r&&(e=r(r=0)),e);var w=(r,e)=>()=>(e||r((e={exports:{}}).exports,e),e.exports),ut=(r,e)=>{for(var t in e)AS(r,t,{get:e[t],enumerable:!0})},Dge=(r,e,t,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let n of Sge(e))!xge.call(r,n)&&n!==t&&AS(r,n,{get:()=>e[n],enumerable:!(i=bge(e,n))||i.enumerable});return r};var Pe=(r,e,t)=>(t=r!=null?Qge(vge(r)):{},Dge(e||!r||!r.__esModule?AS(t,"default",{value:r,enumerable:!0}):t,r));var QK=w((GXe,BK)=>{BK.expor
    
    SyntaxError: Unexpected token {
        at createScript (vm.js:56:10)
        at Object.runInThisContext (vm.js:97:10)
        at Module._compile (module.js:549:28)
        at Object.Module._extensions..js (module.js:586:10)
        at Module.load (module.js:494:32)
        at tryModuleLoad (module.js:453:12)
        at Function.Module._load (module.js:445:3)
        at Module.runMain (module.js:611:10)
        at run (bootstrap_node.js:387:7)
        at startup (bootstrap_node.js:153:9)
    
[I 2024-02-26 08:48:52.553 ServerApp] Saving file at /scripts/Untitled2.ipynb
[I 2024-02-26 08:50:58.202 ServerApp] Saving file at /scripts/Untitled2.ipynb
[E 2024-02-26 08:51:34.088 LabApp] Failed to installed chapyter: code 1
    ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/tiktoken/_tiktoken.cpython-311-x86_64-linux-gnu.so'
    
    
[E 2024-02-26 08:51:34.089 ServerApp] {
      "Host": "localhost:8892",
      "Accept": "*/*",
      "Referer": "http://localhost:8892/lab/tree/scripts/Untitled2.ipynb",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15"
    }
[E 2024-02-26 08:51:34.089 ServerApp] 500 POST /lab/api/extensions?1708966104628 (f406b51829c04f75a21c912f4e62bf04@127.0.0.1) 189263.78ms referer=http://localhost:8892/lab/tree/scripts/Untitled2.ipynb
[I 2024-02-26 08:52:21.170 ServerApp] Saving file at /scripts/Untitled2.ipynb
[E 2024-02-26 08:52:21.527 ServerApp] Uncaught exception POST /api/contents/scripts/Untitled2.ipynb/checkpoints?1708966341396 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8892', method='POST', uri='/api/contents/scripts/Untitled2.ipynb/checkpoints?1708966341396', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/handlers.py", line 304, in post
        checkpoint = await ensure_async(cm.create_checkpoint(path))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/manager.py", line 1068, in create_checkpoint
        return await self.checkpoints.create_checkpoint(self, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/filecheckpoints.py", line 140, in create_checkpoint
        return await self.checkpoint_model(checkpoint_id, dest_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/filecheckpoints.py", line 150, in checkpoint_model
        stats = await run_sync(os.stat, os_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
        return await get_async_backend().run_sync_in_worker_thread(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
        return await future
               ^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
        result = context.run(func, *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/expanse/lustre/projects/jhu152/naglemi/mwas/CpGWAS/scripts/.ipynb_checkpoints/Untitled2-checkpoint.ipynb'
[W 2024-02-26 08:52:21.600 ServerApp] wrote error: 'Unhandled error'
    Traceback (most recent call last):
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/handlers.py", line 304, in post
        checkpoint = await ensure_async(cm.create_checkpoint(path))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/manager.py", line 1068, in create_checkpoint
        return await self.checkpoints.create_checkpoint(self, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/filecheckpoints.py", line 140, in create_checkpoint
        return await self.checkpoint_model(checkpoint_id, dest_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/jupyter_server/services/contents/filecheckpoints.py", line 150, in checkpoint_model
        stats = await run_sync(os.stat, os_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
        return await get_async_backend().run_sync_in_worker_thread(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
        return await future
               ^^^^^^^^^^^^
      File "/home/naglemi/miniconda3/envs/mwas/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
        result = context.run(func, *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/expanse/lustre/projects/jhu152/naglemi/mwas/CpGWAS/scripts/.ipynb_checkpoints/Untitled2-checkpoint.ipynb'
[E 2024-02-26 08:52:21.601 ServerApp] {
      "Host": "localhost:8892",
      "Accept": "*/*",
      "Referer": "http://localhost:8892/lab/tree/scripts/Untitled2.ipynb",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15"
    }
[E 2024-02-26 08:52:21.601 ServerApp] 500 POST /api/contents/scripts/Untitled2.ipynb/checkpoints?1708966341396 (f406b51829c04f75a21c912f4e62bf04@127.0.0.1) 80.20ms referer=http://localhost:8892/lab/tree/scripts/Untitled2.ipynb
[I 2024-02-26 08:52:24.715 ServerApp] Starting buffering for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:ab09df09-e5d3-4206-86ec-323bf48d7a8d
[I 2024-02-26 08:52:24.716 ServerApp] Starting buffering for fbc31e48-4128-4bfc-b740-877a110c5254:0ba6345c-f805-43ec-a232-7a97f7f34385
[I 2024-02-26 08:52:26.792 ServerApp] Connecting to kernel fbc31e48-4128-4bfc-b740-877a110c5254.
[W 2024-02-26 08:52:26.805 LabApp] Could not determine jupyterlab build status without nodejs
[I 2024-02-26 08:52:26.876 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 08:52:26.967 ServerApp] Starting buffering for fbc31e48-4128-4bfc-b740-877a110c5254:da82a062-f632-4a85-915a-6507b5b3a7e0
[I 2024-02-26 08:52:27.046 ServerApp] Starting buffering for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:74770da0-fb39-4d6f-bb53-e7b8061abf49
[I 2024-02-26 08:52:27.957 ServerApp] Connecting to kernel fbc31e48-4128-4bfc-b740-877a110c5254.
[I 2024-02-26 08:52:28.093 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 08:54:27.899 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 08:54:33.774 ServerApp] Kernel restarted: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5
[I 2024-02-26 08:54:33.846 ServerApp] Starting buffering for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 08:54:33.988 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 08:54:33.988 ServerApp] Restoring connection for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 08:56:28.385 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 08:57:43.606 ServerApp] Kernel restarted: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5
[I 2024-02-26 08:57:43.682 ServerApp] Starting buffering for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 08:57:43.815 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 08:57:43.815 ServerApp] Restoring connection for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 08:58:28.750 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:00:31.435 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:02:31.899 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:04:32.234 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:06:32.749 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:08:33.184 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:10:33.574 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:12:34.012 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:14:34.484 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:16:35.076 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:18:35.601 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:20:35.912 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:22:36.403 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:30:37.159 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:34:37.612 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:36:41.954 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:42:42.365 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:46:42.984 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:48:43.432 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:49:16.945 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:51:17.556 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:53:18.147 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:55:18.688 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:55:41.529 ServerApp] Kernel interrupted: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5
[I 2024-02-26 09:57:20.129 ServerApp] Kernel interrupted: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5

Warning message:
In .helpForCall(topicExpr, parent.frame()) :
  no method defined for function ‘$’ and signature ‘x = "data.table"’
Execution halted
[I 2024-02-26 09:58:01.321 ServerApp] Kernel interrupted: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5
[I 2024-02-26 09:58:01.514 ServerApp] Kernel restarted: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5
[I 2024-02-26 09:58:01.744 ServerApp] Starting buffering for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 09:58:01.746 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 09:58:04.127 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 09:58:04.127 ServerApp] Restoring connection for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:02:54.283 ServerApp] Kernel interrupted: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5
[I 2024-02-26 10:02:54.313 ServerApp] Kernel restarted: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5
[I 2024-02-26 10:02:54.386 ServerApp] Starting buffering for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:02:54.497 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 10:02:54.497 ServerApp] Restoring connection for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:04:54.301 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2024-02-26 10:04:54.302 ServerApp] kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5 restarted
[I 2024-02-26 10:04:54.434 ServerApp] Starting buffering for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:04:54.643 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 10:04:54.643 ServerApp] Restoring connection for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:05:37.240 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 10:17:11.984 ServerApp] Kernel restarted: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5
[I 2024-02-26 10:17:12.060 ServerApp] Starting buffering for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:17:12.195 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 10:17:12.196 ServerApp] Restoring connection for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:17:26.975 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2024-02-26 10:17:26.976 ServerApp] kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5 restarted
[I 2024-02-26 10:17:27.051 ServerApp] Starting buffering for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:17:27.192 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 10:17:27.192 ServerApp] Restoring connection for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:17:37.672 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[I 2024-02-26 10:17:40.690 ServerApp] Kernel restarted: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5
[I 2024-02-26 10:17:40.764 ServerApp] Starting buffering for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:17:40.901 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 10:17:40.901 ServerApp] Restoring connection for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:18:43.680 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2024-02-26 10:18:43.681 ServerApp] kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5 restarted
[I 2024-02-26 10:18:43.800 ServerApp] Starting buffering for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:18:43.945 ServerApp] Connecting to kernel b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5.
[I 2024-02-26 10:18:43.945 ServerApp] Restoring connection for b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5:90f6d1a4-cdf8-43da-bbc4-36d33b00fc97
[I 2024-02-26 10:19:08.143 ServerApp] Saving file at /scripts/09_Match_SNP_methylation_files.ipynb
[W 2024-02-26 10:19:15.141 ServerApp] /expanse/lustre/projects/jhu152/naglemi/mwas/CpGWAS/scripts/.~09_Match_SNP_methylation_files.ipynb doesn't exist
slurmstepd: error: *** JOB 28933311 ON exp-1-07 CANCELLED AT 2024-02-26T10:20:15 ***
[C 2024-02-26 10:20:15.454 ServerApp] received signal 15, stopping
[I 2024-02-26 10:20:15.484 ServerApp] Shutting down 5 extensions
[I 2024-02-26 10:20:15.484 ServerApp] Shutting down 2 kernels
[I 2024-02-26 10:20:15.484 ServerApp] Kernel shutdown: fbc31e48-4128-4bfc-b740-877a110c5254
[I 2024-02-26 10:20:15.485 ServerApp] Kernel shutdown: b9a61a43-05a3-4b86-9c6d-ad13dc5c6ce5
slurmstepd: error: Detected 5 oom_kill events in StepId=28933311.batch. Some of the step tasks have been OOM Killed.
